[package]
name = "medi_core"
version = "0.1.4"
edition = "2021"
description = "Medi standard library: core collections and iterator primitives"
license = "Apache-2.0"

[lib]
name = "medi_core"
path = "src/lib.rs"

[dependencies]

[dev-dependencies]
approx = "0.5"
