[build-system]
requires = ["maturin>=1.5,<2.0"]
build-backend = "maturin"

[project]
name = "pymedi"
version = "0.0.17"
requires-python = ">=3.10"

[tool.maturin]
manifest-path = "Cargo.toml"
module-name = "pymedi"
bindings = "pyo3"
